### ISSUE TITLE
Hosting a simple static site on IPFS

### ISSUE THREAD

**Issue by ethers** [giodamelio/giodamelio.github.io#1]
Hi, you posted
https://news.ycombinator.com/item?id=10228293

Looks like IPFS broke your link?
https://gateway.ipfs.io/ipns/QmWGb7PZmLb1TwsMkE1b8jVK4LGceMYMsWaSmviSucWPGG/2015/09/15/hosting-a-website-on-ipfs/

I do see your article at...
https://ipfs.io/ipfs/QmdPtC3T7Kcu9iJg6hYzLBWR5XCDcYMY7HV685E3kH3EcS/2015/09/15/hosting-a-website-on-ipfs/

**Comment by giodamelio** [comment]
Ya, the gateway changed. Also IPNS is not really ready for prime time yet. For now, you need to publish your IPFS hash to IPNS once a day. I was going to set up a cronjob to do it, but I think I will stop using IPNS until is has been fleshed out a bit more. For now you can see my blog at https://blog.giodamelio.com.
